### ISSUE TITLE
怎么好像没效果？

### ISSUE THREAD

**Issue by Zedtion** [Bertramoon/DGUT-Auto-Report#12]
新版登陆系统是不是不能用了

**Comment by Bertramoon** [comment]
是的，暂时因为更换新登录接口用不了，前端进行了AES加密传输，国庆我会看看的，顺利的话应该会在国庆期间更新


| |
bertramoon
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年9月29日 10:10 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [Bertramoon/DGUT-Auto-Report] 怎么好像没效果？ (Issue #12) |

新版登陆系统是不是不能用了

**Comment by Bertramoon** [comment]
已经修改为最新版本，可以使用了
