### ISSUE TITLE
貌似会导致帐号冻结

### ISSUE THREAD

**Issue by snowly233** [Bertramoon/DGUT-Auto-Report#13]
最近我的帐号频繁被冻结，只能找辅导员解开，是由于服务器ip的问题还是什么原因？能拜托作者看一下吗（顺带一提我今天【10/13】才看见打卡系统升级并且我的自动更新系统是打开的但并没有自动更新。而且冻结从10月7号开始出现这种状况）

**Comment by snowly233** [comment]
自动更新失效是PAT失效，冻结原因仍不清楚

**Comment by snowly233** [comment]
另3天自动更新会将custom_data.json用户设定内容自动修改

**Comment by snowly233** [comment]
初步预计是卡验证码了。能否加一个超过多少分钟无法签到成功自动停止运行，然后我预计可以解决帐号冻结的问题

**Comment by Bertramoon** [comment]
针对以上问题：
1. custom_data.json会被更新替换。需求记下，可以为自动更新的朋友加几个和账号密码一样的环境变量，先读取环境变量，没有环境变量再读取文件
2. 账号冻结问题，可能是由于之前老接口登陆不了频繁调用被学校系统封了，更新后你看看还会不会有这种情况。然后你说的卡验证码因为还没遇到过所以暂时也没有解决方案，如果不希望登录失败后继续重试的话，可以把文件`Auto_Report.py`里面的`@retry(tries=20, delay=2, backoff=3, max_delay=60)`删去。目前版本基本稳定，可以先不更新测试一下，这个issues先不关闭，后面更新后我会在这里跟你说一声

**Comment by Bertramoon** [comment]
已更新，可以重新尝试一下，确定没问题之后再关闭该issues

**Comment by snowly233** [comment]
应该是没问题了
