### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by drpasserby** [Bertramoon/DGUT-Auto-Report#8]
报错信息：he server encountere
估计是增加了两个每天需要填报的选项

**Comment by IceWindy233** [comment]
根据爬虫脚本库的文档，在report方法加入custom_data=add_date参数，然后新建一个
```
add_date = {
        "body_temperature": "36.5",
        "health_situation": "1"
}
```
应该就可以解决了，我撤回重填后利用脚本提交的没有问题，但是手里没有没打卡的号了，因此没法尝试每日打卡是否还会出现同样的问题，只能明天再测试（（（

**Comment by Bertramoon** [comment]
了解。首先非常感谢反馈！
因为我现在已经毕业了，需要借号进行测试，因此修复bug会慢一些。如果愿意的话，各位在发现bug后可以提pull，一同持续贡献该项目，感谢

**Comment by drpasserby** [comment]
最新版已解决，issue关闭。
